image: composer/composer:latest

definitions: 
  steps: 
    # common step for assebling composer packages
    - step: &composer_update
        name: Composer update
        image: composer/composer:1
        caches: 
          - composer
        script:
          - composer update
        artifacts:
          - vendor/**
    # common step for building static files into *public/* directory
    - step: &build_static
        name: Build static
        image: node:13.5.0
        caches:
          - node
        script:
          - npm i && yarn prod
        artifacts:
          - public/**

pipelines:
  branches:
    remote-dev:
      - parallel:
        - step:
            <<: *composer_update
        - step:
            <<: *build_static   
      - step:
          name: Deploy to Development
          image: eeacms/rsync
          script:
            - echo "Deploy to Development server"
            - rsync -aclvrzp --no-perms --exclude .git/ --exclude bitbucket-pipelines.yml -e "ssh -p22" ./ $DEV_URL
          
    remote-prod:
      - parallel:
        - step:
            <<: *composer_update
        - step:
            <<: *build_static  
      - step:
          name: Deploy to Production
          image: eeacms/rsync
          script:
            - echo "Deploy to Production server"
            - rsync -aclvrzp --no-perms --exclude .git/ --exclude bitbucket-pipelines.yml -e "ssh -p22" ./ $PROD_URL
